### ISSUE TITLE
Add Travis Config file

### ISSUE THREAD

**Issue by manishprivet** [manishprivet/bookr#12]
We're going to use Travis CI for testing of Pull Requests, as Vercel already handles the deployment part. Travis CI has already been connected to the repo. Now we just need a `.travis.yml` file for automating testing of PRs. 

Possible content for the file is:

```yml
language: node_js

node_js:
  - "14"

script:
  - yarn test
  - yarn run build
```
